/** Generated by @rivi-software/radiotools-sdk-generator — do not edit by hand. */
import { useCallback, useEffect, useRef, useState } from "react";
import type { StationClient } from "@rivi-software/radiotools-sdk";

type QueryState<T> = {
  data: T | undefined;
  error: Error | undefined;
  loading: boolean;
  refresh: () => void;
};

function useStationQuery<T>(
  client: StationClient,
  _method: string,
  read: () => Promise<T>,
): QueryState<T> {
  const [data, setData] = useState<T | undefined>(undefined);
  const [error, setError] = useState<Error | undefined>(undefined);
  const [loading, setLoading] = useState(true);
  const mounted = useRef(true);

  const refresh = useCallback(() => {
    setLoading(true);
    void read()
      .then((value) => {
        if (!mounted.current) return;
        setData(value);
        setError(undefined);
      })
      .catch((cause: unknown) => {
        if (!mounted.current) return;
        setError(cause instanceof Error ? cause : new Error(String(cause)));
      })
      .finally(() => {
        if (mounted.current) setLoading(false);
      });
  }, [read]);

  useEffect(() => {
    mounted.current = true;
    refresh();
    return () => {
      mounted.current = false;
    };
  }, [refresh]);

  return { data, error, loading, refresh };
}

export function useRecommendedPollInterval(client: StationClient): QueryState<number> {
  return useStationQuery(client, "recommendedPollIntervalMs", () =>
    client.recommendedPollIntervalMs(),
  );
}

export function useGetStation(client: StationClient) {
  return useStationQuery(client, "getStation", () => client.getStation());
}

export function useGetCurrentBroadcast(client: StationClient) {
  return useStationQuery(client, "getCurrentBroadcast", () => client.getCurrentBroadcast());
}

export function useGetNowPlaying(client: StationClient) {
  return useStationQuery(client, "getNowPlaying", () => client.getNowPlaying());
}

export function useGetWeather(client: StationClient) {
  return useStationQuery(client, "getWeather", () => client.getWeather());
}

export function useGetTraffic(client: StationClient) {
  return useStationQuery(client, "getTraffic", () => client.getTraffic());
}
