# Generated by @rivi-software/radiotools-sdk-generator — do not edit by hand.
# frozen_string_literal: true

require "json"
require "net/http"
require "uri"

module RadioTools
  class StationClient
    def initialize(base_url:, station_slug:, api_token: nil, ingest_token: nil)
      raise ArgumentError, "api_token or ingest_token is required" if api_token.to_s.empty? && ingest_token.to_s.empty?

      @base_url = base_url.to_s.chomp("/")
      @station_slug = station_slug
      @api_token = api_token
      @ingest_token = ingest_token
    end

    def self.from_env
      new(
        base_url: ENV.fetch("RADIOTOOLS_BASE_URL", ""),
        station_slug: ENV.fetch("RADIOTOOLS_STATION_SLUG", ""),
        api_token: ENV["RADIOTOOLS_API_TOKEN"],
        ingest_token: ENV["RADIOTOOLS_INGEST_TOKEN"],
      )
    end

    def get_station
      get_json("/api/v1/stations/#{URI.encode_uri_component(@station_slug)}", ingest: false)
    end

    def get_weather
      href = station_resource("weather")
      return nil if href.nil? || href.empty?

      get_json(href, ingest: false)
    end

    def get_traffic
      href = station_resource("traffic")
      return nil if href.nil? || href.empty?

      get_json(href, ingest: false)
    end

    def report_playback(observation, station_id: nil)
      params = station_id ? { stationId: station_id } : { stationSlug: @station_slug }
      query = URI.encode_www_form(params)
      post_json("/api/v1/integrations/playback?#{query}", observation, ingest: true)
    end

    private

    def station_resource(key)
      station = get_station
      station.dig("resources", key)
    end

    def get_json(path, ingest:)
      uri = path.start_with?("http") ? URI(path) : URI("#{@base_url}#{path}")
      request = Net::HTTP::Get.new(uri)
      apply_auth!(request, ingest)
      execute(request, uri)
    end

    def post_json(path, body, ingest:)
      uri = URI("#{@base_url}#{path}")
      request = Net::HTTP::Post.new(uri)
      request["Content-Type"] = "application/json"
      request.body = JSON.generate(body)
      apply_auth!(request, ingest)
      execute(request, uri)
    end

    def apply_auth!(request, ingest)
      token = ingest ? @ingest_token : @api_token
      raise ArgumentError, "missing bearer token" if token.to_s.empty?

      request["Authorization"] = "Bearer #{token}"
    end

    def execute(request, uri)
      response = Net::HTTP.start(uri.host, uri.port, use_ssl: uri.scheme == "https") do |http|
        http.request(request)
      end
      raise "HTTP #{response.code}: #{response.body}" unless response.is_a?(Net::HTTPSuccess)

      JSON.parse(response.body)
    end
  end
end
