/** Generated by @rivi-software/radiotools-sdk-generator — do not edit by hand. */
import "server-only";

import {
  createStationClientFromEnv,
  type CreateStationClientOptions,
  type StationClient,
} from "@rivi-software/radiotools-sdk";
import { unstable_cache } from "next/cache";
import { NextResponse } from "next/server";

const DEFAULT_REVALIDATE_SECONDS = 30;

export function createRadioToolsServerClient(
  overrides: Partial<CreateStationClientOptions> = {},
): StationClient {
  return createStationClientFromEnv(undefined, overrides);
}

export function createCachedRadioToolsReader<T>(
  cacheKey: string,
  read: (client: StationClient) => Promise<T>,
  revalidateSeconds: number = DEFAULT_REVALIDATE_SECONDS,
) {
  return unstable_cache(async () => read(createRadioToolsServerClient()), [cacheKey], {
    revalidate: revalidateSeconds,
  });
}

export async function fetchGetStation(client: StationClient) {
  return client.getStation();
}

export async function fetchGetCurrentBroadcast(client: StationClient) {
  return client.getCurrentBroadcast();
}

export async function fetchGetNowPlaying(client: StationClient) {
  return client.getNowPlaying();
}

export async function fetchGetWeather(client: StationClient) {
  return client.getWeather();
}

export async function fetchGetTraffic(client: StationClient) {
  return client.getTraffic();
}

export async function fetchRecommendedPollIntervalMs(client: StationClient) {
  return client.recommendedPollIntervalMs();
}

export const cachedGetStation = createCachedRadioToolsReader("radiotools:station", (c) => c.getStation());
export const cachedGetNowPlaying = createCachedRadioToolsReader("radiotools:now-playing", (c) =>
  c.getNowPlaying(),
);
export const cachedGetCurrentBroadcast = createCachedRadioToolsReader(
  "radiotools:current-broadcast",
  (c) => c.getCurrentBroadcast(),
);

/** App Router helper for `/api/radiotools/-station` */
export async function jsonResponseStation(client: StationClient) {
  const data = await client.getStation();
  return NextResponse.json(data);
}

/** App Router helper for `/api/radiotools/-current-broadcast` */
export async function jsonResponseCurrentBroadcast(client: StationClient) {
  const data = await client.getCurrentBroadcast();
  return NextResponse.json(data);
}

/** App Router helper for `/api/radiotools/-now-playing` */
export async function jsonResponseNowPlaying(client: StationClient) {
  const data = await client.getNowPlaying();
  return NextResponse.json(data);
}

/** App Router helper for `/api/radiotools/-weather` */
export async function jsonResponseWeather(client: StationClient) {
  const data = await client.getWeather();
  return NextResponse.json(data);
}

/** App Router helper for `/api/radiotools/-traffic` */
export async function jsonResponseTraffic(client: StationClient) {
  const data = await client.getTraffic();
  return NextResponse.json(data);
}

export type { StationClient, CreateStationClientOptions };
