import { listenerSdkManifest } from "@rivi-software/radiotools-contract";
import type { SdkTarget } from "../types";

function renderKotlinClient(): string {
  const manifest = listenerSdkManifest;
  return `// Generated by @rivi-software/radiotools-sdk-generator — do not edit by hand.
package com.radiotools.sdk

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.put
import okhttp3.HttpUrl.Companion.toHttpUrl
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import okhttp3.MediaType.Companion.toMediaType
import java.io.IOException
import java.util.concurrent.TimeUnit

class StationClient private constructor(
    private val baseUrl: String,
    private val stationSlug: String,
    private val apiToken: String?,
    private val ingestToken: String?,
    private val http: OkHttpClient,
    private val json: Json,
) {
    companion object {
        fun create(
            baseUrl: String,
            stationSlug: String,
            apiToken: String? = null,
            ingestToken: String? = null,
            http: OkHttpClient? = null,
        ): StationClient {
            require(!apiToken.isNullOrBlank() || !ingestToken.isNullOrBlank()) {
                "apiToken or ingestToken is required"
            }
            val client =
                http
                    ?: OkHttpClient.Builder()
                        .connectTimeout(30, TimeUnit.SECONDS)
                        .readTimeout(30, TimeUnit.SECONDS)
                        .build()
            return StationClient(
                baseUrl.trimEnd('/'),
                stationSlug,
                apiToken?.trim()?.takeIf { it.isNotEmpty() },
                ingestToken?.trim()?.takeIf { it.isNotEmpty() },
                client,
                Json { ignoreUnknownKeys = true },
            )
        }
    }

    @Throws(IOException::class)
    fun getStation(): JsonObject = getJson("/api/v1/stations/\${encode(stationSlug)}", ingest = false)

    @Throws(IOException::class)
    fun getNowPlaying(): JsonObject {
        val station = getStation()
        val href =
            station["resources"]?.let { it as? JsonObject }?.get("nowPlaying")?.toString()?.trim('"')
                ?: error("nowPlaying resource unavailable")
        return getJson(href, ingest = false)
    }

    @Throws(IOException::class)
    fun getWeather(): JsonObject? {
        val href =
            getStation()["resources"]?.let { it as? JsonObject }?.get("weather")?.toString()?.trim('"')
        if (href.isNullOrEmpty()) return null
        return getJson(href, ingest = false)
    }

    @Throws(IOException::class)
    fun getTraffic(): JsonObject? {
        val href =
            getStation()["resources"]?.let { it as? JsonObject }?.get("traffic")?.toString()?.trim('"')
        if (href.isNullOrEmpty()) return null
        return getJson(href, ingest = false)
    }

    @Throws(IOException::class)
    fun reportPlayback(observation: JsonObject, stationId: String? = null): JsonObject {
        val query =
            if (!stationId.isNullOrBlank()) {
                "stationId=\${encode(stationId)}"
            } else {
                "stationSlug=\${encode(stationSlug)}"
            }
        val path = "${manifest.integrations.playback.path}?\$query"
        return postJson(path, observation, ingest = true)
    }

    private fun getJson(path: String, ingest: Boolean): JsonObject {
        val url = if (path.startsWith("http")) path else "\$baseUrl\$path"
        val request =
            Request.Builder()
                .url(url.toHttpUrl())
                .header("Authorization", bearer(ingest))
                .get()
                .build()
        http.newCall(request).execute().use { response ->
            val body = response.body?.string() ?: "{}"
            if (!response.isSuccessful) error("GET \${'$'}url failed: \${response.code} \${'$'}body")
            return json.decodeFromString(JsonObject.serializer(), body)
        }
    }

    private fun postJson(path: String, body: JsonObject, ingest: Boolean): JsonObject {
        val url = "\$baseUrl\$path".toHttpUrl()
        val mediaType = "application/json; charset=utf-8".toMediaType()
        val payload = json.encodeToString(JsonObject.serializer(), body)
        val request =
            Request.Builder()
                .url(url)
                .header("Authorization", bearer(ingest))
                .post(payload.toRequestBody(mediaType))
                .build()
        http.newCall(request).execute().use { response ->
            val text = response.body?.string() ?: "{}"
            if (!response.isSuccessful) error("POST \${'$'}url failed: \${response.code} \${'$'}text")
            return json.decodeFromString(JsonObject.serializer(), text)
        }
    }

    private fun bearer(ingest: Boolean): String {
        val token = if (ingest) ingestToken else apiToken
        require(!token.isNullOrBlank()) { "Missing bearer token" }
        return "Bearer \$token"
    }

    private fun encode(value: String): String =
        java.net.URLEncoder.encode(value, Charsets.UTF_8.name()).replace("+", "%20")
}
`;
}

export const kotlinTarget: SdkTarget = {
  id: "kotlin",
  description: "Kotlin/Android OkHttp client stubs (packages/sdk-kotlin)",
  outputDir: (repoRoot) => `${repoRoot}/packages/sdk-kotlin/src/main/kotlin/com/radiotools/sdk`,
  generate: (repoRoot) => [
    { path: "StationClient.kt", contents: renderKotlinClient() },
    {
      path: `${repoRoot}/packages/sdk-kotlin/build.gradle.kts`,
      contents: `plugins {
    kotlin("jvm") version "2.1.0"
    kotlin("plugin.serialization") version "2.1.0"
}

group = "com.radiotools"
version = "0.2.0"

repositories {
    mavenCentral()
}

dependencies {
    implementation("com.squareup.okhttp3:okhttp:4.12.0")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.8.0")
}

kotlin {
    jvmToolchain(17)
}
`,
    },
    {
      path: `${repoRoot}/packages/sdk-kotlin/README.md`,
      contents: `# RadioTools Kotlin SDK

Generated Android/JVM REST stubs (OkHttp + kotlinx.serialization).

Regenerate: \`bun run --filter @rivi-software/radiotools-sdk-generator generate --target kotlin\`

OpenAPI models: see \`packages/openapi/openapi.json\` (from Zod \`sdkSchemas\`).
`,
    },
  ],
};
