import { ZERO_ARG_READ_METHODS } from "../shared/reads";
import type { SdkTarget } from "../types";

function renderNextServerHelpers(): string {
  const cachedReads = ZERO_ARG_READ_METHODS.map((method) => {
    const fnName = `fetch${method.charAt(0).toUpperCase()}${method.slice(1)}`;
    return `export async function ${fnName}(client: StationClient) {
  return client.${method}();
}`;
  }).join("\n\n");

  const routeHandlers = ZERO_ARG_READ_METHODS.map((method) => {
    const suffix = method.replace(/^get/, "");
    const exportName = `jsonResponse${suffix}`;
    const routeName = suffix.replace(/([A-Z])/g, "-$1").toLowerCase();
    return `/** App Router helper for \`/api/radiotools/${routeName}\` */
export async function ${exportName}(client: StationClient) {
  const data = await client.${method}();
  return NextResponse.json(data);
}`;
  }).join("\n\n");

  return `/** Generated by @rivi-software/radiotools-sdk-generator — do not edit by hand. */
import "server-only";

import {
  createStationClientFromEnv,
  type CreateStationClientOptions,
  type StationClient,
} from "@rivi-software/radiotools-sdk";
import { unstable_cache } from "next/cache";
import { NextResponse } from "next/server";

const DEFAULT_REVALIDATE_SECONDS = 30;

export function createRadioToolsServerClient(
  overrides: Partial<CreateStationClientOptions> = {},
): StationClient {
  return createStationClientFromEnv(undefined, overrides);
}

export function createCachedRadioToolsReader<T>(
  cacheKey: string,
  read: (client: StationClient) => Promise<T>,
  revalidateSeconds: number = DEFAULT_REVALIDATE_SECONDS,
) {
  return unstable_cache(async () => read(createRadioToolsServerClient()), [cacheKey], {
    revalidate: revalidateSeconds,
  });
}

${cachedReads}

export async function fetchRecommendedPollIntervalMs(client: StationClient) {
  return client.recommendedPollIntervalMs();
}

export const cachedGetStation = createCachedRadioToolsReader("radiotools:station", (c) => c.getStation());
export const cachedGetNowPlaying = createCachedRadioToolsReader("radiotools:now-playing", (c) =>
  c.getNowPlaying(),
);
export const cachedGetCurrentBroadcast = createCachedRadioToolsReader(
  "radiotools:current-broadcast",
  (c) => c.getCurrentBroadcast(),
);

${routeHandlers}

export type { StationClient, CreateStationClientOptions };
`;
}

export const nextTarget: SdkTarget = {
  id: "next",
  description: "Next.js App Router server helpers (packages/sdk-next)",
  outputDir: (repoRoot) => `${repoRoot}/packages/sdk-next/src`,
  generate: () => [
    { path: "server.generated.ts", contents: renderNextServerHelpers() },
    {
      path: "index.ts",
      contents: `export * from "./server.generated";
`,
    },
  ],
};
