import { listenerSdkManifest } from "@rivi-software/radiotools-contract";
import { snakeCase } from "../shared/naming";
import type { SdkTarget } from "../types";

function renderPythonClient(): string {
  const manifest = listenerSdkManifest;
  const readMethods = manifest.clientMethods.filter(
    (m) => m.scope === "listener:read" && m.rest?.method === "GET" && m.name.startsWith("get"),
  );

  const methodBlocks = readMethods
    .map((method) => {
      const pyName = snakeCase(method.name);
      if (method.name === "getStation") {
        return `    def ${pyName}(self) -> dict[str, Any]:
        """${method.description}"""
        return self._get_json(f"/api/v1/stations/{quote(self.station_slug, safe='')}")`;
      }
      if (method.name === "getWeather" || method.name === "getTraffic") {
        return `    def ${pyName}(self) -> dict[str, Any] | None:
        """${method.description}"""
        station = self.get_station()
        href = station.get("resources", {}).get("${method.name === "getWeather" ? "weather" : "traffic"}")
        if not href:
            return None
        return self._get_json(href)`;
      }
      return `    def ${pyName}(self, **params: Any) -> dict[str, Any]:
        """${method.description}"""
        raise NotImplementedError("Use the TypeScript SDK or extend this stub with REST href resolution.")`;
    })
    .join("\n\n");

  return `"""Generated by @rivi-software/radiotools-sdk-generator — do not edit by hand."""
from __future__ import annotations

from typing import Any
from urllib.parse import quote

import httpx


class RadioToolsStationClient:
    """Minimal REST client for RadioTools listener contract v${manifest.contractVersion}."""

    def __init__(
        self,
        base_url: str,
        station_slug: str,
        *,
        api_token: str | None = None,
        ingest_token: str | None = None,
        client: httpx.Client | None = None,
    ) -> None:
        if not api_token and not ingest_token:
            raise ValueError("api_token or ingest_token is required")
        self.base_url = base_url.rstrip("/")
        self.station_slug = station_slug
        self.api_token = api_token
        self.ingest_token = ingest_token
        self._client = client or httpx.Client(timeout=30.0)

    def _headers(self, *, ingest: bool = False) -> dict[str, str]:
        token = self.ingest_token if ingest else self.api_token
        if not token:
            scope = "ingest:write" if ingest else "listener:read"
            raise ValueError(f"Missing token for {scope}")
        return {"Authorization": f"Bearer {token}"}

    def _get_json(self, path: str, *, params: dict[str, Any] | None = None) -> dict[str, Any]:
        url = path if path.startswith("http") else f"{self.base_url}{path}"
        response = self._client.get(
            url,
            params=params,
            headers=self._headers(),
        )
        response.raise_for_status()
        return response.json()

    def _post_json(self, path: str, body: dict[str, Any], *, ingest: bool = True) -> dict[str, Any]:
        url = f"{self.base_url}{path}"
        response = self._client.post(url, json=body, headers=self._headers(ingest=ingest))
        response.raise_for_status()
        return response.json()

${methodBlocks}

    def report_playback(self, observation: dict[str, Any], *, station_id: str | None = None) -> dict[str, Any]:
        """Send one encoder playback observation."""
        params: dict[str, str] = {}
        if station_id:
            params["stationId"] = station_id
        else:
            params["stationSlug"] = self.station_slug
        path = "${manifest.integrations.playback.path}"
        query = "&".join(f"{k}={quote(v, safe='')}" for k, v in params.items())
        return self._post_json(f"{path}?{query}", observation)

    @classmethod
    def from_env(cls) -> RadioToolsStationClient:
        import os

        base_url = os.environ.get("RADIOTOOLS_BASE_URL", "").strip()
        station_slug = os.environ.get("RADIOTOOLS_STATION_SLUG", "").strip()
        api_token = os.environ.get("RADIOTOOLS_API_TOKEN", "").strip() or None
        ingest_token = os.environ.get("RADIOTOOLS_INGEST_TOKEN", "").strip() or None
        if not base_url or not station_slug:
            raise ValueError("Set RADIOTOOLS_BASE_URL and RADIOTOOLS_STATION_SLUG")
        return cls(base_url, station_slug, api_token=api_token, ingest_token=ingest_token)
`;
}

export const pythonTarget: SdkTarget = {
  id: "python",
  description: "Python httpx client stubs (packages/sdk-python)",
  outputDir: (repoRoot) => `${repoRoot}/packages/sdk-python/src/radiotools_sdk`,
  generate: () => [
    {
      path: "client.py",
      contents: renderPythonClient(),
    },
    {
      path: "__init__.py",
      contents: `"""${listenerSdkManifest.packageNames.python} — generated listener SDK."""
from .client import RadioToolsStationClient

__all__ = ["RadioToolsStationClient"]
`,
    },
  ],
};
