import type { SdkTarget } from "../types";
import { hookNameFromMethod, ZERO_ARG_READ_METHODS } from "../shared/reads";

function renderReactHooks(): string {
  const hooks = ZERO_ARG_READ_METHODS.map((method) => {
    const hookName = hookNameFromMethod(method);
    return `export function ${hookName}(client: StationClient) {
  return useStationQuery(client, "${method}", () => client.${method}());
}`;
  }).join("\n\n");

  return `/** Generated by @radiotools/sdk-generator — do not edit by hand. */
import { useCallback, useEffect, useRef, useState } from "react";
import type { StationClient } from "@radiotools/sdk";

type QueryState<T> = {
  data: T | undefined;
  error: Error | undefined;
  loading: boolean;
  refresh: () => void;
};

function useStationQuery<T>(
  client: StationClient,
  _method: string,
  read: () => Promise<T>,
): QueryState<T> {
  const [data, setData] = useState<T | undefined>(undefined);
  const [error, setError] = useState<Error | undefined>(undefined);
  const [loading, setLoading] = useState(true);
  const mounted = useRef(true);

  const refresh = useCallback(() => {
    setLoading(true);
    void read()
      .then((value) => {
        if (!mounted.current) return;
        setData(value);
        setError(undefined);
      })
      .catch((cause: unknown) => {
        if (!mounted.current) return;
        setError(cause instanceof Error ? cause : new Error(String(cause)));
      })
      .finally(() => {
        if (mounted.current) setLoading(false);
      });
  }, [read]);

  useEffect(() => {
    mounted.current = true;
    refresh();
    return () => {
      mounted.current = false;
    };
  }, [refresh]);

  return { data, error, loading, refresh };
}

export function useRecommendedPollInterval(client: StationClient): QueryState<number> {
  return useStationQuery(client, "recommendedPollIntervalMs", () =>
    client.recommendedPollIntervalMs(),
  );
}

${hooks}
`;
}

export const reactTarget: SdkTarget = {
  id: "react",
  description: "React hooks wrapping @radiotools/sdk (packages/sdk-react)",
  outputDir: (repoRoot) => `${repoRoot}/packages/sdk-react/src`,
  generate: () => [
    {
      path: "hooks.generated.ts",
      contents: renderReactHooks(),
    },
    {
      path: "index.ts",
      contents: `export * from "./hooks.generated";
`,
    },
  ],
};
