import type { SdkTarget } from "../types";
import { pascalCase } from "../shared/naming";
import { ZERO_ARG_READ_METHODS } from "../shared/reads";

function renderSvelteStores(): string {
  const stores = ZERO_ARG_READ_METHODS.map((method) => {
    const storeFn = `create${pascalCase(method)}Store`;
    return `export function ${storeFn}(client: StationClient) {
  return createStationStore(() => client.${method}());
}`;
  }).join("\n\n");

  return `/** Generated by @radiotools/sdk-generator — do not edit by hand. */
import { derived, writable, type Readable } from "svelte/store";
import type { StationClient } from "@radiotools/sdk";

export type StationStoreState<T> = {
  data: T | undefined;
  error: Error | undefined;
  loading: boolean;
};

export type StationStore<T> = Readable<StationStoreState<T>> & {
  refresh: () => Promise<void>;
};

function createStationStore<T>(read: () => Promise<T>): StationStore<T> {
  const inner = writable<StationStoreState<T>>({
    data: undefined,
    error: undefined,
    loading: true,
  });

  const refresh = async () => {
    inner.update((state) => ({ ...state, loading: true }));
    try {
      const data = await read();
      inner.set({ data, error: undefined, loading: false });
    } catch (cause: unknown) {
      inner.set({
        data: undefined,
        error: cause instanceof Error ? cause : new Error(String(cause)),
        loading: false,
      });
    }
  };

  void refresh();

  return {
    subscribe: inner.subscribe,
    refresh,
  };
}

export function createRecommendedPollIntervalStore(client: StationClient) {
  return createStationStore(() => client.recommendedPollIntervalMs());
}

${stores}

/** Convenience derived store: true when any nested field is loading. */
export function stationStoreLoading<T>(store: StationStore<T>): Readable<boolean> {
  return derived(store, ($state) => $state.loading);
}
`;
}

export const svelteTarget: SdkTarget = {
  id: "svelte",
  description: "Svelte stores wrapping @radiotools/sdk (packages/sdk-svelte)",
  outputDir: (repoRoot) => `${repoRoot}/packages/sdk-svelte/src`,
  generate: () => [
    { path: "stores.generated.ts", contents: renderSvelteStores() },
    {
      path: "index.ts",
      contents: `export * from "./stores.generated";\n`,
    },
  ],
};
