import type { SdkTarget } from "../types";
import { hookNameFromMethod, ZERO_ARG_READ_METHODS } from "../shared/reads";

function renderVueComposables(): string {
  const composables = ZERO_ARG_READ_METHODS.map((method) => {
    const name = hookNameFromMethod(method);
    return `export function ${name}(client: StationClient) {
  return useStationQuery(() => client.${method}());
}`;
  }).join("\n\n");

  return `/** Generated by @radiotools/sdk-generator — do not edit by hand. */
import { type Ref, onMounted, onUnmounted, ref, shallowRef } from "vue";
import type { StationClient } from "@radiotools/sdk";

export type StationQuery<T> = {
  data: Ref<T | undefined>;
  error: Ref<Error | undefined>;
  loading: Ref<boolean>;
  refresh: () => Promise<void>;
};

function useStationQuery<T>(read: () => Promise<T>): StationQuery<T> {
  const data = shallowRef<T | undefined>(undefined);
  const error = ref<Error | undefined>(undefined);
  const loading = ref(true);
  let active = true;

  const refresh = async () => {
    loading.value = true;
    try {
      const value = await read();
      if (!active) return;
      data.value = value;
      error.value = undefined;
    } catch (cause: unknown) {
      if (!active) return;
      error.value = cause instanceof Error ? cause : new Error(String(cause));
    } finally {
      if (active) loading.value = false;
    }
  };

  onMounted(() => {
    active = true;
    void refresh();
  });
  onUnmounted(() => {
    active = false;
  });

  return { data, error, loading, refresh };
}

export function useRecommendedPollInterval(client: StationClient): StationQuery<number> {
  return useStationQuery(() => client.recommendedPollIntervalMs());
}

${composables}
`;
}

export const vueTarget: SdkTarget = {
  id: "vue",
  description: "Vue composables wrapping @radiotools/sdk (packages/sdk-vue)",
  outputDir: (repoRoot) => `${repoRoot}/packages/sdk-vue/src`,
  generate: () => [
    { path: "composables.generated.ts", contents: renderVueComposables() },
    { path: "index.ts", contents: `export * from "./composables.generated";\n` },
  ],
};
