// Generated by @rivi-software/radiotools-sdk-generator — do not edit by hand.
using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Text.Json;

namespace RadioTools.Sdk;

public sealed class StationClient : IDisposable
{
    private readonly HttpClient _http;
    private readonly string _baseUrl;
    private readonly string _stationSlug;
    private readonly string? _apiToken;
    private readonly string? _ingestToken;

    public StationClient(string baseUrl, string stationSlug, string? apiToken = null, string? ingestToken = null, HttpClient? http = null)
    {
        if (string.IsNullOrWhiteSpace(apiToken) && string.IsNullOrWhiteSpace(ingestToken))
            throw new ArgumentException("apiToken or ingestToken is required");
        _baseUrl = baseUrl.TrimEnd('/');
        _stationSlug = stationSlug;
        _apiToken = apiToken;
        _ingestToken = ingestToken;
        _http = http ?? new HttpClient { Timeout = TimeSpan.FromSeconds(30) };
    }

    public static StationClient FromEnvironment()
    {
        var baseUrl = Environment.GetEnvironmentVariable("RADIOTOOLS_BASE_URL") ?? "";
        var slug = Environment.GetEnvironmentVariable("RADIOTOOLS_STATION_SLUG") ?? "";
        var api = Environment.GetEnvironmentVariable("RADIOTOOLS_API_TOKEN");
        var ingest = Environment.GetEnvironmentVariable("RADIOTOOLS_INGEST_TOKEN");
        if (string.IsNullOrWhiteSpace(baseUrl) || string.IsNullOrWhiteSpace(slug))
            throw new InvalidOperationException("Set RADIOTOOLS_BASE_URL and RADIOTOOLS_STATION_SLUG");
        return new StationClient(baseUrl, slug, api, ingest);
    }

    public async Task<JsonElement> GetStationAsync(CancellationToken cancellationToken = default)
    {
        var path = $"/api/v1/stations/{Uri.EscapeDataString(_stationSlug)}";
        return await GetJsonAsync(path, ingest: false, cancellationToken);
    }

    public async Task<JsonElement?> GetWeatherAsync(CancellationToken cancellationToken = default)
    {
        var station = await GetStationAsync(cancellationToken);
        if (!station.TryGetProperty("resources", out var resources)) return null;
        if (!resources.TryGetProperty("weather", out var hrefProp)) return null;
        var href = hrefProp.GetString();
        if (string.IsNullOrEmpty(href)) return null;
        return await GetJsonAsync(href, ingest: false, cancellationToken);
    }

    public async Task<JsonElement?> GetTrafficAsync(CancellationToken cancellationToken = default)
    {
        var station = await GetStationAsync(cancellationToken);
        if (!station.TryGetProperty("resources", out var resources)) return null;
        if (!resources.TryGetProperty("traffic", out var hrefProp)) return null;
        var href = hrefProp.GetString();
        if (string.IsNullOrEmpty(href)) return null;
        return await GetJsonAsync(href, ingest: false, cancellationToken);
    }

    public async Task<JsonElement> ReportPlaybackAsync(object observation, string? stationId = null, CancellationToken cancellationToken = default)
    {
        var query = stationId is not null
            ? $"?stationId={Uri.EscapeDataString(stationId)}"
            : $"?stationSlug={Uri.EscapeDataString(_stationSlug)}";
        var url = $"{_baseUrl}/api/v1/integrations/playback{query}";
        using var request = new HttpRequestMessage(HttpMethod.Post, url)
        {
            Content = JsonContent.Create(observation),
        };
        ApplyAuth(request, ingest: true);
        using var response = await _http.SendAsync(request, cancellationToken);
        response.EnsureSuccessStatusCode();
        await using var stream = await response.Content.ReadAsStreamAsync(cancellationToken);
        return await JsonSerializer.DeserializeAsync<JsonElement>(stream, cancellationToken: cancellationToken)
            ?? throw new InvalidOperationException("empty playback response");
    }

    private async Task<JsonElement> GetJsonAsync(string path, bool ingest, CancellationToken cancellationToken)
    {
        var url = path.StartsWith("http", StringComparison.OrdinalIgnoreCase) ? path : $"{_baseUrl}{path}";
        using var request = new HttpRequestMessage(HttpMethod.Get, url);
        ApplyAuth(request, ingest);
        using var response = await _http.SendAsync(request, cancellationToken);
        response.EnsureSuccessStatusCode();
        await using var stream = await response.Content.ReadAsStreamAsync(cancellationToken);
        return await JsonSerializer.DeserializeAsync<JsonElement>(stream, cancellationToken: cancellationToken)
            ?? throw new InvalidOperationException("empty JSON response");
    }

    private void ApplyAuth(HttpRequestMessage request, bool ingest)
    {
        var token = ingest ? _ingestToken : _apiToken;
        if (string.IsNullOrWhiteSpace(token))
            throw new InvalidOperationException("Missing bearer token");
        request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token);
    }

    public void Dispose() => _http.Dispose();
}
