/** Generated by @rivi-software/radiotools-sdk-generator — do not edit by hand. */
import { type Ref, onMounted, onUnmounted, ref, shallowRef } from "vue";
import type { StationClient } from "@rivi-software/radiotools-sdk";

export type StationQuery<T> = {
  data: Ref<T | undefined>;
  error: Ref<Error | undefined>;
  loading: Ref<boolean>;
  refresh: () => Promise<void>;
};

function useStationQuery<T>(read: () => Promise<T>): StationQuery<T> {
  const data = shallowRef<T | undefined>(undefined);
  const error = ref<Error | undefined>(undefined);
  const loading = ref(true);
  let active = true;

  const refresh = async () => {
    loading.value = true;
    try {
      const value = await read();
      if (!active) return;
      data.value = value;
      error.value = undefined;
    } catch (cause: unknown) {
      if (!active) return;
      error.value = cause instanceof Error ? cause : new Error(String(cause));
    } finally {
      if (active) loading.value = false;
    }
  };

  onMounted(() => {
    active = true;
    void refresh();
  });
  onUnmounted(() => {
    active = false;
  });

  return { data, error, loading, refresh };
}

export function useRecommendedPollInterval(client: StationClient): StationQuery<number> {
  return useStationQuery(() => client.recommendedPollIntervalMs());
}

export function useGetStation(client: StationClient) {
  return useStationQuery(() => client.getStation());
}

export function useGetCurrentBroadcast(client: StationClient) {
  return useStationQuery(() => client.getCurrentBroadcast());
}

export function useGetNowPlaying(client: StationClient) {
  return useStationQuery(() => client.getNowPlaying());
}

export function useGetWeather(client: StationClient) {
  return useStationQuery(() => client.getWeather());
}

export function useGetTraffic(client: StationClient) {
  return useStationQuery(() => client.getTraffic());
}
