<?php
// Generated by @rivi-software/radiotools-sdk-generator — do not edit by hand.
declare(strict_types=1);

namespace RadioTools\Sdk;

final class StationClient
{
    public function __construct(
        private readonly string $baseUrl,
        private readonly string $stationSlug,
        private readonly ?string $apiToken = null,
        private readonly ?string $ingestToken = null,
    ) {
        if (($this->apiToken ?? '') === '' && ($this->ingestToken ?? '') === '') {
            throw new \InvalidArgumentException('apiToken or ingestToken is required');
        }
    }

    public static function fromEnv(): self
    {
        $base = trim(getenv('RADIOTOOLS_BASE_URL') ?: '');
        $slug = trim(getenv('RADIOTOOLS_STATION_SLUG') ?: '');
        if ($base === '' || $slug === '') {
            throw new \RuntimeException('Set RADIOTOOLS_BASE_URL and RADIOTOOLS_STATION_SLUG');
        }
        return new self(
            $base,
            $slug,
            getenv('RADIOTOOLS_API_TOKEN') ?: null,
            getenv('RADIOTOOLS_INGEST_TOKEN') ?: null,
        );
    }

    /** @return array<string, mixed> */
    public function getStation(): array
    {
        $path = '/api/v1/stations/' . rawurlencode($this->stationSlug);
        return $this->getJson($path, ingest: false);
    }

    /** @return array<string, mixed>|null */
    public function getWeather(): ?array
    {
        $station = $this->getStation();
        $href = $station['resources']['weather'] ?? null;
        if (!is_string($href) || $href === '') {
            return null;
        }
        return $this->getJson($href, ingest: false);
    }

    /** @return array<string, mixed>|null */
    public function getTraffic(): ?array
    {
        $station = $this->getStation();
        $href = $station['resources']['traffic'] ?? null;
        if (!is_string($href) || $href === '') {
            return null;
        }
        return $this->getJson($href, ingest: false);
    }

    /** @param array<string, mixed> $observation
     *  @return array<string, mixed>
     */
    public function reportPlayback(array $observation, ?string $stationId = null): array
    {
        $query = $stationId !== null
            ? 'stationId=' . rawurlencode($stationId)
            : 'stationSlug=' . rawurlencode($this->stationSlug);
        return $this->postJson('/api/v1/integrations/playback?' . $query, $observation, ingest: true);
    }

    /** @return array<string, mixed> */
    private function getJson(string $path, bool $ingest): array
    {
        $url = str_starts_with($path, 'http') ? $path : rtrim($this->baseUrl, '/') . $path;
        return $this->request('GET', $url, null, $ingest);
    }

    /** @param array<string, mixed> $body
     *  @return array<string, mixed>
     */
    private function postJson(string $path, array $body, bool $ingest): array
    {
        $url = rtrim($this->baseUrl, '/') . $path;
        return $this->request('POST', $url, json_encode($body, JSON_THROW_ON_ERROR), $ingest);
    }

    /** @return array<string, mixed> */
    private function request(string $method, string $url, ?string $body, bool $ingest): array
    {
        $token = $ingest ? $this->ingestToken : $this->apiToken;
        if ($token === null || $token === '') {
            throw new \RuntimeException('Missing bearer token');
        }

        $ch = curl_init($url);
        if ($ch === false) {
            throw new \RuntimeException('curl_init failed');
        }

        $headers = [
            'Authorization: Bearer ' . $token,
            'Accept: application/json',
        ];
        if ($body !== null) {
            $headers[] = 'Content-Type: application/json';
        }

        curl_setopt_array($ch, [
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_CUSTOMREQUEST => $method,
            CURLOPT_HTTPHEADER => $headers,
            CURLOPT_POSTFIELDS => $body,
        ]);

        $raw = curl_exec($ch);
        $code = (int) curl_getinfo($ch, CURLINFO_RESPONSE_CODE);
        curl_close($ch);

        if ($raw === false || $code >= 400) {
            throw new \RuntimeException("HTTP {$code}: " . (string) $raw);
        }

        /** @var array<string, mixed> */
        return json_decode($raw, true, 512, JSON_THROW_ON_ERROR);
    }
}
