// Generated by @rivi-software/radiotools-sdk-generator — do not edit by hand.
import Foundation

public enum RadioToolsSDKError: Error, LocalizedError {
    case missingToken
    case invalidURL
    case httpStatus(Int, String)

    public var errorDescription: String? {
        switch self {
        case .missingToken: return "Missing bearer token"
        case .invalidURL: return "Invalid URL"
        case let .httpStatus(code, body): return "HTTP \(code): \(body)"
        }
    }
}

public final class StationClient: @unchecked Sendable {
    private let baseURL: URL
    private let stationSlug: String
    private let apiToken: String?
    private let ingestToken: String?
    private let session: URLSession

    public init(
        baseURL: URL,
        stationSlug: String,
        apiToken: String? = nil,
        ingestToken: String? = nil,
        session: URLSession = .shared
    ) throws {
        guard apiToken?.isEmpty == false || ingestToken?.isEmpty == false else {
            throw RadioToolsSDKError.missingToken
        }
        self.baseURL = baseURL
        self.stationSlug = stationSlug
        self.apiToken = apiToken
        self.ingestToken = ingestToken
        self.session = session
    }

    public func getStation() async throws -> [String: Any] {
        let path = "/api/v1/stations/\(stationSlug.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? stationSlug)"
        return try await getJSON(path: path, ingest: false)
    }

    public func getNowPlaying() async throws -> [String: Any] {
        let station = try await getStation()
        guard
            let resources = station["resources"] as? [String: Any],
            let href = resources["nowPlaying"] as? String,
            !href.isEmpty
        else {
            throw RadioToolsSDKError.httpStatus(404, "nowPlaying unavailable")
        }
        return try await getJSON(path: href, ingest: false)
    }

    public func getWeather() async throws -> [String: Any]? {
        let station = try await getStation()
        guard
            let resources = station["resources"] as? [String: Any],
            let href = resources["weather"] as? String,
            !href.isEmpty
        else { return nil }
        return try await getJSON(path: href, ingest: false)
    }

    public func getTraffic() async throws -> [String: Any]? {
        let station = try await getStation()
        guard
            let resources = station["resources"] as? [String: Any],
            let href = resources["traffic"] as? String,
            !href.isEmpty
        else { return nil }
        return try await getJSON(path: href, ingest: false)
    }

    public func reportPlayback(
        observation: [String: Any],
        stationId: String? = nil
    ) async throws -> [String: Any] {
        var items: [URLQueryItem] = []
        if let stationId, !stationId.isEmpty {
            items.append(URLQueryItem(name: "stationId", value: stationId))
        } else {
            items.append(URLQueryItem(name: "stationSlug", value: stationSlug))
        }
        var components = URLComponents(url: baseURL.appendingPathComponent("api/v1/integrations/playback"), resolvingAgainstBaseURL: false)
        components?.queryItems = items
        guard let url = components?.url else { throw RadioToolsSDKError.invalidURL }
        return try await postJSON(url: url, body: observation, ingest: true)
    }

    private func getJSON(path: String, ingest: Bool) async throws -> [String: Any] {
        let url: URL
        if path.hasPrefix("http") {
            guard let parsed = URL(string: path) else { throw RadioToolsSDKError.invalidURL }
            url = parsed
        } else {
            url = URL(string: path, relativeTo: baseURL)?.absoluteURL ?? baseURL
        }
        var request = URLRequest(url: url)
        request.httpMethod = "GET"
        request.setValue(try bearer(ingest: ingest), forHTTPHeaderField: "Authorization")
        let (data, response) = try await session.data(for: request)
        try validate(response: response, data: data)
        let object = try JSONSerialization.jsonObject(with: data)
        guard let dict = object as? [String: Any] else { return [:] }
        return dict
    }

    private func postJSON(url: URL, body: [String: Any], ingest: Bool) async throws -> [String: Any] {
        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.setValue(try bearer(ingest: ingest), forHTTPHeaderField: "Authorization")
        request.httpBody = try JSONSerialization.data(withJSONObject: body)
        let (data, response) = try await session.data(for: request)
        try validate(response: response, data: data)
        let object = try JSONSerialization.jsonObject(with: data)
        return object as? [String: Any] ?? [:]
    }

    private func bearer(ingest: Bool) throws -> String {
        let token = ingest ? ingestToken : apiToken
        guard let token, !token.isEmpty else { throw RadioToolsSDKError.missingToken }
        return "Bearer \(token)"
    }

    private func validate(response: URLResponse, data: Data) throws {
        guard let http = response as? HTTPURLResponse else { return }
        guard (200 ... 299).contains(http.statusCode) else {
            let body = String(data: data, encoding: .utf8) ?? ""
            throw RadioToolsSDKError.httpStatus(http.statusCode, body)
        }
    }
}
