// Generated by @radiotools/sdk-generator — do not edit by hand.
package radiotools

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"strings"
	"time"
)

type StationClient struct {
	BaseURL     string
	StationSlug string
	APIToken    string
	IngestToken string
	HTTPClient  *http.Client
}

func NewStationClient(baseURL, stationSlug, apiToken, ingestToken string) (*StationClient, error) {
	if apiToken == "" && ingestToken == "" {
		return nil, fmt.Errorf("apiToken or ingestToken is required")
	}
	return &StationClient{
		BaseURL:     strings.TrimRight(baseURL, "/"),
		StationSlug: stationSlug,
		APIToken:    apiToken,
		IngestToken: ingestToken,
		HTTPClient:  &http.Client{Timeout: 30 * time.Second},
	}, nil
}

func StationClientFromEnv() (*StationClient, error) {
	baseURL := strings.TrimSpace(os.Getenv("RADIOTOOLS_BASE_URL"))
	slug := strings.TrimSpace(os.Getenv("RADIOTOOLS_STATION_SLUG"))
	apiToken := strings.TrimSpace(os.Getenv("RADIOTOOLS_API_TOKEN"))
	ingestToken := strings.TrimSpace(os.Getenv("RADIOTOOLS_INGEST_TOKEN"))
	if baseURL == "" || slug == "" {
		return nil, fmt.Errorf("set RADIOTOOLS_BASE_URL and RADIOTOOLS_STATION_SLUG")
	}
	return NewStationClient(baseURL, slug, apiToken, ingestToken)
}

func (c *StationClient) getJSON(ctx context.Context, path string, ingest bool) (map[string]any, error) {
	target := path
	if !strings.HasPrefix(path, "http") {
		target = c.BaseURL + path
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, target, nil)
	if err != nil {
		return nil, err
	}
	token := c.APIToken
	if ingest {
		token = c.IngestToken
	}
	if token == "" {
		return nil, fmt.Errorf("missing bearer token")
	}
	req.Header.Set("Authorization", "Bearer "+token)
	res, err := c.HTTPClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer res.Body.Close()
	if res.StatusCode >= 400 {
		body, _ := io.ReadAll(res.Body)
		return nil, fmt.Errorf("GET %s: %s (%s)", target, res.Status, strings.TrimSpace(string(body)))
	}
	var payload map[string]any
	if err := json.NewDecoder(res.Body).Decode(&payload); err != nil {
		return nil, err
	}
	return payload, nil
}

func (c *StationClient) GetStation(ctx context.Context) (map[string]any, error) {
	path := fmt.Sprintf("/api/v1/stations/%s", url.PathEscape(c.StationSlug))
	return c.getJSON(ctx, path, false)
}

func (c *StationClient) GetWeather(ctx context.Context) (map[string]any, error) {
	station, err := c.GetStation(ctx)
	if err != nil {
		return nil, err
	}
	resources, _ := station["resources"].(map[string]any)
	if resources == nil {
		return nil, nil
	}
	href, _ := resources["weather"].(string)
	if href == "" {
		return nil, nil
	}
	return c.getJSON(ctx, href, false)
}

func (c *StationClient) GetTraffic(ctx context.Context) (map[string]any, error) {
	station, err := c.GetStation(ctx)
	if err != nil {
		return nil, err
	}
	resources, _ := station["resources"].(map[string]any)
	if resources == nil {
		return nil, nil
	}
	href, _ := resources["traffic"].(string)
	if href == "" {
		return nil, nil
	}
	return c.getJSON(ctx, href, false)
}

func (c *StationClient) ReportPlayback(ctx context.Context, observation map[string]any, stationID string) (map[string]any, error) {
	q := url.Values{}
	if stationID != "" {
		q.Set("stationId", stationID)
	} else {
		q.Set("stationSlug", c.StationSlug)
	}
	target := c.BaseURL + "/api/v1/integrations/playback?" + q.Encode()
	body, err := json.Marshal(observation)
	if err != nil {
		return nil, err
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, target, bytes.NewReader(body))
	if err != nil {
		return nil, err
	}
	if c.IngestToken == "" {
		return nil, fmt.Errorf("ingest token required")
	}
	req.Header.Set("Authorization", "Bearer "+c.IngestToken)
	req.Header.Set("Content-Type", "application/json")
	res, err := c.HTTPClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer res.Body.Close()
	if res.StatusCode >= 400 {
		raw, _ := io.ReadAll(res.Body)
		return nil, fmt.Errorf("POST playback: %s (%s)", res.Status, strings.TrimSpace(string(raw)))
	}
	var payload map[string]any
	if err := json.NewDecoder(res.Body).Decode(&payload); err != nil {
		return nil, err
	}
	return payload, nil
}
