/** Generated by @radiotools/sdk-generator — do not edit by hand. */
import { derived, writable, type Readable } from "svelte/store";
import type { StationClient } from "@radiotools/sdk";

export type StationStoreState<T> = {
  data: T | undefined;
  error: Error | undefined;
  loading: boolean;
};

export type StationStore<T> = Readable<StationStoreState<T>> & {
  refresh: () => Promise<void>;
};

function createStationStore<T>(read: () => Promise<T>): StationStore<T> {
  const inner = writable<StationStoreState<T>>({
    data: undefined,
    error: undefined,
    loading: true,
  });

  const refresh = async () => {
    inner.update((state) => ({ ...state, loading: true }));
    try {
      const data = await read();
      inner.set({ data, error: undefined, loading: false });
    } catch (cause: unknown) {
      inner.set({
        data: undefined,
        error: cause instanceof Error ? cause : new Error(String(cause)),
        loading: false,
      });
    }
  };

  void refresh();

  return {
    subscribe: inner.subscribe,
    refresh,
  };
}

export function createRecommendedPollIntervalStore(client: StationClient) {
  return createStationStore(() => client.recommendedPollIntervalMs());
}

export function createGetStationStore(client: StationClient) {
  return createStationStore(() => client.getStation());
}

export function createGetCurrentBroadcastStore(client: StationClient) {
  return createStationStore(() => client.getCurrentBroadcast());
}

export function createGetNowPlayingStore(client: StationClient) {
  return createStationStore(() => client.getNowPlaying());
}

export function createGetWeatherStore(client: StationClient) {
  return createStationStore(() => client.getWeather());
}

export function createGetTrafficStore(client: StationClient) {
  return createStationStore(() => client.getTraffic());
}

/** Convenience derived store: true when any nested field is loading. */
export function stationStoreLoading<T>(store: StationStore<T>): Readable<boolean> {
  return derived(store, ($state) => $state.loading);
}
